# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cet6_listener.protos.tts import preset_voice_pb2 as cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cet6_listener/protos/tts/preset_voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresetVoiceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPresetVoices = channel.unary_unary(
                '/qwen_tts.service.v1.PresetVoiceService/ListPresetVoices',
                request_serializer=cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesRequest.SerializeToString,
                response_deserializer=cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesResponse.FromString,
                _registered_method=True)


class PresetVoiceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListPresetVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresetVoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPresetVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPresetVoices,
                    request_deserializer=cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesRequest.FromString,
                    response_serializer=cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qwen_tts.service.v1.PresetVoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qwen_tts.service.v1.PresetVoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresetVoiceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPresetVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_tts.service.v1.PresetVoiceService/ListPresetVoices',
            cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesRequest.SerializeToString,
            cet6__listener_dot_protos_dot_tts_dot_preset__voice__pb2.ListPresetVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
