# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cet6_listener/protos/tts/preset_voice.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cet6_listener/protos/tts/preset_voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+cet6_listener/protos/tts/preset_voice.proto\x12\x13qwen_tts.service.v1\"\x19\n\x17ListPresetVoicesRequest\"\x98\x01\n\x0fPresetVoiceInfo\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x1b\n\x13supports_synthesize\x18\x04 \x01(\x08\x12\x17\n\x0fsupports_duplex\x18\x05 \x01(\x08\x12\x1d\n\x15\x61vailable_on_instance\x18\x06 \x01(\x08\"f\n\x18ListPresetVoicesResponse\x12\x34\n\x06voices\x18\x01 \x03(\x0b\x32$.qwen_tts.service.v1.PresetVoiceInfo\x12\x14\n\x0cserving_mode\x18\x02 \x01(\t2\x85\x01\n\x12PresetVoiceService\x12o\n\x10ListPresetVoices\x12,.qwen_tts.service.v1.ListPresetVoicesRequest\x1a-.qwen_tts.service.v1.ListPresetVoicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cet6_listener.protos.tts.preset_voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTPRESETVOICESREQUEST']._serialized_start=68
  _globals['_LISTPRESETVOICESREQUEST']._serialized_end=93
  _globals['_PRESETVOICEINFO']._serialized_start=96
  _globals['_PRESETVOICEINFO']._serialized_end=248
  _globals['_LISTPRESETVOICESRESPONSE']._serialized_start=250
  _globals['_LISTPRESETVOICESRESPONSE']._serialized_end=352
  _globals['_PRESETVOICESERVICE']._serialized_start=355
  _globals['_PRESETVOICESERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
